/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "comp_case.v:3.1-12.10" *)
module comp_case(i0, i1, i2, sel, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "comp_case.v:3.25-3.27" *)
  wire _06_;
  (* src = "comp_case.v:3.36-3.38" *)
  wire _07_;
  (* src = "comp_case.v:3.47-3.49" *)
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "comp_case.v:3.64-3.67" *)
  wire _11_;
  (* src = "comp_case.v:3.64-3.67" *)
  wire _12_;
  (* src = "comp_case.v:3.80-3.81" *)
  wire _13_;
  (* src = "comp_case.v:3.25-3.27" *)
  input i0;
  wire i0;
  (* src = "comp_case.v:3.36-3.38" *)
  input i1;
  wire i1;
  (* src = "comp_case.v:3.47-3.49" *)
  input i2;
  wire i2;
  (* src = "comp_case.v:3.64-3.67" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "comp_case.v:3.80-3.81" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2i_1 _14_ (
    .A0(_06_),
    .A1(_07_),
    .S(_11_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _15_ (
    .A(_12_),
    .B(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _16_ (
    .A1(_12_),
    .A2(_09_),
    .B1(_10_),
    .Y(_13_)
  );
  assign _12_ = sel[1];
  assign _11_ = sel[0];
  assign _07_ = i1;
  assign _06_ = i0;
  assign _08_ = i2;
  assign y = _13_;
endmodule
