/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "demux_for.v:2.1-14.10" *)
module demux_for(o0, o1, o2, o3, o4, o5, o6, o7, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "demux_for.v:2.136-2.137" *)
  wire _13_;
  (* src = "demux_for.v:2.26-2.28" *)
  wire _14_;
  (* src = "demux_for.v:2.38-2.40" *)
  wire _15_;
  (* src = "demux_for.v:2.49-2.51" *)
  wire _16_;
  (* src = "demux_for.v:2.61-2.63" *)
  wire _17_;
  (* src = "demux_for.v:2.72-2.74" *)
  wire _18_;
  (* src = "demux_for.v:2.83-2.85" *)
  wire _19_;
  (* src = "demux_for.v:2.94-2.96" *)
  wire _20_;
  (* src = "demux_for.v:2.106-2.108" *)
  wire _21_;
  (* src = "demux_for.v:2.123-2.126" *)
  wire _22_;
  (* src = "demux_for.v:2.123-2.126" *)
  wire _23_;
  (* src = "demux_for.v:2.123-2.126" *)
  wire _24_;
  (* src = "demux_for.v:2.136-2.137" *)
  input i;
  wire i;
  (* src = "demux_for.v:5.9-5.10" *)
  wire [31:0] k;
  (* src = "demux_for.v:2.26-2.28" *)
  output o0;
  wire o0;
  (* src = "demux_for.v:2.38-2.40" *)
  output o1;
  wire o1;
  (* src = "demux_for.v:2.49-2.51" *)
  output o2;
  wire o2;
  (* src = "demux_for.v:2.61-2.63" *)
  output o3;
  wire o3;
  (* src = "demux_for.v:2.72-2.74" *)
  output o4;
  wire o4;
  (* src = "demux_for.v:2.83-2.85" *)
  output o5;
  wire o5;
  (* src = "demux_for.v:2.94-2.96" *)
  output o6;
  wire o6;
  (* src = "demux_for.v:2.106-2.108" *)
  output o7;
  wire o7;
  (* src = "demux_for.v:2.123-2.126" *)
  input [2:0] sel;
  wire [2:0] sel;
  (* src = "demux_for.v:3.10-3.15" *)
  wire [7:0] y_int;
  sky130_fd_sc_hd__and4_1 _25_ (
    .A(_24_),
    .B(_22_),
    .C(_23_),
    .D(_13_),
    .X(_21_)
  );
  sky130_fd_sc_hd__and4b_1 _26_ (
    .A_N(_22_),
    .B(_23_),
    .C(_13_),
    .D(_24_),
    .X(_20_)
  );
  sky130_fd_sc_hd__and4b_1 _27_ (
    .A_N(_23_),
    .B(_13_),
    .C(_24_),
    .D(_22_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nor4bb_1 _28_ (
    .A(_22_),
    .B(_23_),
    .C_N(_13_),
    .D_N(_24_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and4b_1 _29_ (
    .A_N(_24_),
    .B(_22_),
    .C(_23_),
    .D(_13_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nor4bb_1 _30_ (
    .A(_24_),
    .B(_22_),
    .C_N(_23_),
    .D_N(_13_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor4bb_1 _31_ (
    .A(_24_),
    .B(_23_),
    .C_N(_13_),
    .D_N(_22_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor4b_1 _32_ (
    .A(_24_),
    .B(_22_),
    .C(_23_),
    .D_N(_13_),
    .Y(_14_)
  );
  assign k = 32'd8;
  assign y_int = { o7, o6, o5, o4, o3, o2, o1, o0 };
  assign _24_ = sel[2];
  assign _22_ = sel[0];
  assign _23_ = sel[1];
  assign _13_ = i;
  assign o7 = _21_;
  assign o6 = _20_;
  assign o5 = _19_;
  assign o4 = _18_;
  assign o3 = _17_;
  assign o2 = _16_;
  assign o1 = _15_;
  assign o0 = _14_;
endmodule
