/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "demux_case.v:1.1-20.10" *)
module demux_case(o0, o1, o2, o3, o4, o5, o6, o7, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "demux_case.v:1.137-1.138" *)
  wire _35_;
  (* src = "demux_case.v:1.27-1.29" *)
  wire _36_;
  (* src = "demux_case.v:1.39-1.41" *)
  wire _37_;
  (* src = "demux_case.v:1.50-1.52" *)
  wire _38_;
  (* src = "demux_case.v:1.62-1.64" *)
  wire _39_;
  (* src = "demux_case.v:1.73-1.75" *)
  wire _40_;
  (* src = "demux_case.v:1.84-1.86" *)
  wire _41_;
  (* src = "demux_case.v:1.95-1.97" *)
  wire _42_;
  (* src = "demux_case.v:1.107-1.109" *)
  wire _43_;
  (* src = "demux_case.v:1.124-1.127" *)
  wire _44_;
  (* src = "demux_case.v:1.124-1.127" *)
  wire _45_;
  (* src = "demux_case.v:1.124-1.127" *)
  wire _46_;
  (* src = "demux_case.v:1.137-1.138" *)
  input i;
  wire i;
  (* src = "demux_case.v:1.27-1.29" *)
  output o0;
  wire o0;
  (* src = "demux_case.v:1.39-1.41" *)
  output o1;
  wire o1;
  (* src = "demux_case.v:1.50-1.52" *)
  output o2;
  wire o2;
  (* src = "demux_case.v:1.62-1.64" *)
  output o3;
  wire o3;
  (* src = "demux_case.v:1.73-1.75" *)
  output o4;
  wire o4;
  (* src = "demux_case.v:1.84-1.86" *)
  output o5;
  wire o5;
  (* src = "demux_case.v:1.95-1.97" *)
  output o6;
  wire o6;
  (* src = "demux_case.v:1.107-1.109" *)
  output o7;
  wire o7;
  (* src = "demux_case.v:1.124-1.127" *)
  input [2:0] sel;
  wire [2:0] sel;
  (* src = "demux_case.v:2.10-2.15" *)
  wire [7:0] y_int;
  sky130_fd_sc_hd__and4b_1 _47_ (
    .A_N(_44_),
    .B(_35_),
    .C(_46_),
    .D(_45_),
    .X(_42_)
  );
  sky130_fd_sc_hd__and4b_1 _48_ (
    .A_N(_45_),
    .B(_44_),
    .C(_35_),
    .D(_46_),
    .X(_41_)
  );
  sky130_fd_sc_hd__and4b_1 _49_ (
    .A_N(_46_),
    .B(_45_),
    .C(_44_),
    .D(_35_),
    .X(_39_)
  );
  sky130_fd_sc_hd__nor4bb_1 _50_ (
    .A(_46_),
    .B(_45_),
    .C_N(_44_),
    .D_N(_35_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__nor4bb_1 _51_ (
    .A(_46_),
    .B(_44_),
    .C_N(_35_),
    .D_N(_45_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nor4bb_1 _52_ (
    .A(_45_),
    .B(_44_),
    .C_N(_35_),
    .D_N(_46_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nor4b_1 _53_ (
    .A(_46_),
    .B(_45_),
    .C(_44_),
    .D_N(_35_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__and4_1 _54_ (
    .A(_46_),
    .B(_45_),
    .C(_44_),
    .D(_35_),
    .X(_43_)
  );
  assign y_int = { o7, o6, o5, o4, o3, o2, o1, o0 };
  assign _46_ = sel[2];
  assign _45_ = sel[1];
  assign _44_ = sel[0];
  assign _35_ = i;
  assign o6 = _42_;
  assign o5 = _41_;
  assign o3 = _39_;
  assign o1 = _37_;
  assign o2 = _38_;
  assign o4 = _40_;
  assign o0 = _36_;
  assign o7 = _43_;
endmodule
