/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "incomp_if2.v:2.1-11.10" *)
module incomp_if2(i0, i1, i2, i3, y);
  (* src = "incomp_if2.v:3.1-10.4" *)
  wire _00_;
  wire _01_;
  (* src = "incomp_if2.v:3.1-10.4" *)
  wire _02_;
  wire _03_;
  (* src = "incomp_if2.v:2.26-2.28" *)
  wire _04_;
  (* src = "incomp_if2.v:2.37-2.39" *)
  wire _05_;
  (* src = "incomp_if2.v:2.48-2.50" *)
  wire _06_;
  (* src = "incomp_if2.v:2.59-2.61" *)
  wire _07_;
  (* src = "incomp_if2.v:2.26-2.28" *)
  input i0;
  wire i0;
  (* src = "incomp_if2.v:2.37-2.39" *)
  input i1;
  wire i1;
  (* src = "incomp_if2.v:2.48-2.50" *)
  input i2;
  wire i2;
  (* src = "incomp_if2.v:2.59-2.61" *)
  input i3;
  wire i3;
  (* src = "incomp_if2.v:2.74-2.75" *)
  output y;
  reg y;
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(_07_),
    .A1(_05_),
    .S(_04_),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _09_ (
    .A(_04_),
    .B(_06_),
    .Y(_03_)
  );
  (* src = "incomp_if2.v:3.1-10.4" *)
  always @*
    if (!_01_) y = _00_;
  assign _07_ = i3;
  assign _05_ = i1;
  assign _04_ = i0;
  assign _00_ = _02_;
  assign _06_ = i2;
  assign _01_ = _03_;
endmodule
