/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "incomp_if.v:1.1-7.10" *)
module incomp_if(i0, i1, i2, y);
  (* src = "incomp_if.v:1.25-1.27" *)
  input i0;
  wire i0;
  (* src = "incomp_if.v:1.36-1.38" *)
  input i1;
  wire i1;
  (* src = "incomp_if.v:1.47-1.49" *)
  input i2;
  wire i2;
  (* src = "incomp_if.v:1.63-1.64" *)
  output y;
  reg y;
  (* src = "incomp_if.v:2.1-6.4" *)
  always @*
    if (i0) y = i1;
endmodule
